name: Run lint && check

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm ci
        
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
