
name: Check Pull Request Code

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm ci
        
      - name: Lint
        run: npm run lint
      
      - name: Test
        run: npm run test
